# Generated by Django 4.0.5 on 2022-06-13 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adress_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='Secretary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.secretary'),
        ),
        migrations.AddField(
            model_name='institution',
            name='cnpj',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
