# Generated by Django 4.0.5 on 2022-06-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('user', models.CharField(choices=[('ESTUDANTE', 'ESTUDANTE'), ('SECRETARIA', 'SECRETARIA'), ('PROFESSOR', 'PROFESSOR')], default='ESTUDANTE', max_length=255)),
                ('sex', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('cpf', models.CharField(max_length=255, null=True)),
                ('registration', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('specialization', models.CharField(max_length=255, null=True)),
                ('class_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class_school')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_school',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='Secretary',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='institution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
